print('Hello WORLD')
print('Hello WORLD''\'')
print('Hello WORLD' + ' CCC')
print('Hello WORLD','CCC')
print('Hello WORLD',' CCC')
print('Hello WORLD','CCC','CCC','CCC','CCC','CCC','CCC','CCC', sep='*')
print('Hello WORLD','CCC','CCC','CCC','CCC','CCC','CCC','CCC', sep=' ')
print('Hello WORLD','CCC','CCC','CCC','CCC','CCC','CCC','CCC', sep='')
print(2+3)
print('2+3')
print('     2+3 \n     XXX\n         ZZZ')
